## 🌟 Exercise 1 : Array Creation and Manipulation
### Instructions
Create a 1D NumPy array containing numbers from 0 to 9.

In [5]:
import numpy as np

In [6]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 🌟 Exercise 2 : Type Conversion and Array Operations
### Instructions
Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.

In [7]:
lst = [3.14, 2.17, 0, 1, 2]
arr = np.array(lst).astype(int)
arr

array([3, 2, 0, 1, 2])

## 🌟 Exercise 3 : Working with Multi-Dimensional Arrays
### Instructions
Create a 3x3 NumPy array with values ranging from 1 to 9.

In [8]:
arr = np.arange(1,10).reshape((3,3))
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 🌟 Exercise 4 : Creating Multi-Dimensional Array with Random Numbers
### Instructions
Create a 2D NumPy array of shape (4, 5) filled with random numbers.

In [10]:
np.random.seed(42)
arr = np.random.random((4,5)).round(2)
arr

array([[0.37, 0.95, 0.73, 0.6 , 0.16],
       [0.16, 0.06, 0.87, 0.6 , 0.71],
       [0.02, 0.97, 0.83, 0.21, 0.18],
       [0.18, 0.3 , 0.52, 0.43, 0.29]])

## 🌟 Exercise 5 : Indexing Arrays
### Instructions
Select the second row from a given 2D NumPy array.

In [15]:
arr = np.arange(1,10).reshape(3,3)
print("Array:")
print(arr)
print()
print("Second row:")
print(arr[1, :])

Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Second row:
[4 5 6]


## 🌟 Exercise 6 : Reversing elements
### Instructions
Reverse the order of elements in a given 1D NumPy array (first element becomes last).

In [19]:
arr = np.arange(10)
print("Original array:")
print(arr)
print()

new_arr = arr[::-1]
print("New Array:")
print(new_arr)

Original array:
[0 1 2 3 4 5 6 7 8 9]

New Array:
[9 8 7 6 5 4 3 2 1 0]


## 🌟 Exercise 7 : Identity Matrix
### Instructions
Create a 4x4 identity matrix using NumPy.

In [22]:
ident = np.eye(4)
print(ident)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## 🌟 Exercise 8 : Simple Aggregate Funcs
### Instructions
Find the sum and average of a given 1D array.

In [23]:
arr = np.arange(10)
print("Array:")
print(arr)
print()

print("Sum of elements:")
print(arr.sum())
print

print("Average of elements:")
print(arr.mean())

Array:
[0 1 2 3 4 5 6 7 8 9]

Sum of elements:
45
Average of elements:
4.5


## 🌟 Exercise 9 : Create Array and Change its Structure
### Instructions
Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

In [24]:
arr = np.arange(1,21)
print("1D array")
print(arr)
arr = arr.reshape(4,5)
print("2D array:")
print(arr)


1D array
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
2D array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


## 🌟 Exercise 10 : Conditional Selection of Values
### Instructions
Extract all odd numbers from a given NumPy array.

In [25]:
arr = np.arange(10)
print("Array:")
print(arr)
print("Odd numbers:")
print(arr[arr % 2 == 1])

Array:
[0 1 2 3 4 5 6 7 8 9]
Odd numbers:
[1 3 5 7 9]
